# Les Modules et les packages en python

## Les Modules en python

### Créer son propre module

In [1]:
# Importer et renommer tout le module
from monPackage import spyderPython4 as desc

In [2]:
# création de la liste
chiffre_affaires = [30, 40, 50, 80, 100]

In [3]:
# Application de la fonction
desc.statdescriptive(chiffre_affaires)

{'min': 30, 'max': 100, 'somme': 300, 'moyenne': 60.0}

In [4]:
# somme du chiffre d'affaire
somme_ca = desc.sommme_element(chiffre_affaires)
somme_ca

300

In [5]:
# importer une partie du module
from monPackage.spyderPython4 import statdescriptive,sommme_element

In [6]:
statdescriptive(chiffre_affaires)

{'min': 30, 'max': 100, 'somme': 300, 'moyenne': 60.0}

In [7]:
# sommme_element n'a pas été importer
sommme_element(chiffre_affaires)

300

## Les modules externes

Exemple de structure ici: https://docs.python.org/fr/3/tutorial/modules.html#

Ensemble des modules https://docs.python.org/3/py-modindex.html

Quelques modules utiles en data science

math: Pour les fonctions mathématiques de base.
statistics Pour faire des statistiques
os: Pour interagir avec le système d'exploitation, comme la gestion des chemins de fichiers et les commandes du système d'exploitation.
sys: Fournit un accès à certaines variables et fonctions qui interagissent fortement avec l'interpréteur Python.
json: Pour la lecture et l'écriture de données au format JSON.
csv: Pour lire et écrire des fichiers CSV.
datetime: Pour manipuler les dates et les heures.
random: Pour la génération de nombres aléatoires.
re: Pour les expressions régulières, utiles dans le traitement de texte et le nettoyage des données.
sqlite3: Pour la gestion de bases de données SQL légères.
pickle: Pour la sérialisation et la désérialisation de structures de données Python.

In [8]:
import math

In [9]:
print("racine carré: ",math.sqrt(90))
print("cosinus:",math.cos(90))
print("sinus:",math.sin(90))
print("exponentiel",math.exp(90))

racine carré:  9.486832980505138
cosinus: -0.4480736161291701
sinus: 0.8939966636005579
exponentiel 1.2204032943178408e+39


In [10]:
# ex d'utilisation des modules statistiques
import statistics as st

In [11]:
print(st.mean([30,50,60]))
print(st.median_high([30,50,60]))

46.666666666666664
50


In [12]:
# ex d'utilisation de random (choice, seed, sample, randint, shuffle)
import random

In [13]:
# choisir un élément aléatoire dans une liste (liste de nom)
liste_nom = ["R", "T", "M", "A"]
random.choice(liste_nom)

'T'

In [14]:
# fixer la graine (seed) 
random.seed(51)
liste_nom = ["R", "T", "M", "A"]
random.choice(liste_nom)

'T'

In [15]:
# sample
random.sample(["R", "T"], counts=[6,2], k=8)
# sample(range(10000), 60)

['R', 'R', 'T', 'R', 'T', 'R', 'R', 'R']

In [16]:
# aléatoire float (random.random)
random.random()

0.5860643734085744

In [17]:
# aléatoire interger
random.randint(1,100)

47

In [18]:
# choisir un nombre d'élément à partir d'un liste et choisir un nombre précis

In [19]:
# Mélanger aléatoirement des données dans une liste (shuffle)
random.shuffle(liste_nom)
liste_nom

['R', 'M', 'T', 'A']

## Les packages en python
Lien pour en sarvoir plus https://packaging.python.org/en/latest/tutorials/packaging-projects/

# utilisation de mon package

In [20]:
import monPackage.spyderPython4 as sp

Trouver les packages disponibles ici: https://pypi.org/

In [21]:
!pip list

Package                       Version
----------------------------- ---------------
absl-py                       2.1.0
alabaster                     0.7.12
anaconda-client               1.11.1
anaconda-navigator            2.4.0
anaconda-project              0.11.1
ansi2html                     1.9.1
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.14.2
astropy                       5.1
asttokens                     2.0.5
astunparse                    1.6.3
atomicwrites                  1.4.0
attrs                         22.1.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.11.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
beautif

Trouver les packages disponibles ici: https://pypi.org/

In [22]:
# Installer un package
!pip install tensorflow

In [23]:
import numpy as np

In [24]:
from monPackage.spyderPython4 import statdescriptive
# import statdescriptive from monPackage.spyderPython4 . faux !

# Open

In [25]:
# ecrire dans le ficher et créer le ficher (première approche)

In [26]:
f = open("resultat.txt", "w")
f.write("Bonjour")
f.close()

In [27]:
f = open("resultat.txt", "r")
f.read()


'Bonjour'

In [28]:
f.close()

In [29]:
# ecriture 2 apporche avec with
with open("resultat2.txt", "w") as f:
    for i in range(1,10):
        f.write(f"Le prochain nombre est {i} \n")

In [30]:
# lecture 2 approche (readlines et read().splitlines())
with open("resultat2.txt", "r") as f:
    resultat = f.readlines()
resultat

['Le prochain nombre est 1 \n',
 'Le prochain nombre est 2 \n',
 'Le prochain nombre est 3 \n',
 'Le prochain nombre est 4 \n',
 'Le prochain nombre est 5 \n',
 'Le prochain nombre est 6 \n',
 'Le prochain nombre est 7 \n',
 'Le prochain nombre est 8 \n',
 'Le prochain nombre est 9 \n']

In [31]:
#importer avec la technique des listes en compréhension

# Bien démarrer avec Numpy

## Bien démarrer avec une dimention(Create)

In [32]:
# shape

In [33]:
# importation
import numpy as np

In [34]:
# Création d'un nd array à une dimension à partir d'une liste
tableau_dim1 = np.array([4,5,2,6,6,4,8,5561,8,1,6,8])
tableau_dim1

array([   4,    5,    2,    6,    6,    4,    8, 5561,    8,    1,    6,
          8])

In [35]:
tableau_dim1 = np.array([[4,5,2,6,6,4,8],[4,5,2,6,6,4,8]])
tableau_dim1

array([[4, 5, 2, 6, 6, 4, 8],
       [4, 5, 2, 6, 6, 4, 8]])

In [36]:
type(tableau_dim1.shape)

tuple

In [37]:
# shape de l'objet

In [38]:
# nombre d'élément dans le tableau size de l'objet

In [39]:
# attributs importants: shape et size

## créer un numpy array à partir des fonctions intégrées

In [40]:
# tableau avec des zéros (np.zeros)
tableau_zero = np.zeros((2,2))
tableau_zero

array([[0., 0.],
       [0., 0.]])

In [41]:
# tableau avec des uns (np.ones)
tableau_ones = np.ones((3,3))
tableau_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.eye??

In [43]:
# créer une matrice identité avec np.eyes()
tableau_eye = np.eye(3)
tableau_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
# créer un numpy array avec la fonction arange: pour créer des nombre entre le minimum et le maximum avec un pas
np.arange(0,22,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [45]:
# créer un numpy array avec la fonction linspace 
# générer une séquence de nombre 
# très utile pour les graphiques
# entre deux valeurs données avec un nombre de points donné
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [50]:
# Créer un numpy array de valeurs aléatoires avec la fonction random avec np.random.random
np.random.random(10)

array([0.59975217, 0.32880715, 0.85259554, 0.83240943, 0.17556442,
       0.71915193, 0.01868748, 0.50657277, 0.09357181, 0.06601439])

In [ ]:
# nombre aléatoire suivant une loi aléatoire
# fixer la graine avec seed de random

# Accéder aux éléments, sélectionner(read)

In [51]:
# Accès aux éléments
tableau_dim1 = np.array([4,5,2,6,6,4,8,5561,8,1,6,8])
tableau_dim1

array([   4,    5,    2,    6,    6,    4,    8, 5561,    8,    1,    6,
          8])

In [52]:
tableau_dim1[-1]

8

In [58]:
# sélection des éléments qui respectent une condition
tableau_dim1 < 6

array([ True,  True,  True, False, False,  True, False, False, False,
        True, False, False])

In [ ]:
# utilisation de np.where()
np.where(tableau_dim1>7)
nb_superieur_10 = tableau_dim1[np.where(tableau_dim1>7)]
print(nb_superieur_10)

In [ ]:
# récupérer des éléments à partir des indices

# modifier et mettre à un numpy array(Update)